# "files" section allows you to inject custom files like EsiClient.ts
files:
  esi-client.mustache:
    destinationFilename: esi-client.ts
  AccessTokenGet.mustache:
    destinationFilename: models/AccessTokenGet.ts
  SSO.mustache:
    destinationFilename: apis/SSO.ts
  README.mustache:
    destinationFilename: README.md